zope.exceptions-5.2-py3.11-nspkg.pth,sha256=SWEVH-jEWsKYrL0qoC6GBJaStx_iKxGoAY9PQycFVC4,529
zope.exceptions-5.2.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
zope.exceptions-5.2.dist-info/LICENSE.txt,sha256=PmcdsR32h1FswdtbPWXkqjg-rKPCDOo_r1Og9zNdCjw,2070
zope.exceptions-5.2.dist-info/METADATA,sha256=VtJmDE82Dm2ij2ZEr5g93IBeQZIaaNA_I5iyjtelCOg,8685
zope.exceptions-5.2.dist-info/RECORD,,
zope.exceptions-5.2.dist-info/WHEEL,sha256=oiQVh_5PnQM0E3gPdiz09WCNmwiHDMaGer_elqB3coM,92
zope.exceptions-5.2.dist-info/namespace_packages.txt,sha256=QpUHvpO4wIuZDeEgKY8qZCtD-tAukB0fn_f6utzlb98,5
zope.exceptions-5.2.dist-info/top_level.txt,sha256=QpUHvpO4wIuZDeEgKY8qZCtD-tAukB0fn_f6utzlb98,5
zope/exceptions/__init__.py,sha256=Cke9GBvE4nP-9dhCd4V171fjkK_JcnBO0X_X7zFeDdU,2189
zope/exceptions/__pycache__/__init__.cpython-312.pyc,,
zope/exceptions/__pycache__/exceptionformatter.cpython-312.pyc,,
zope/exceptions/__pycache__/interfaces.cpython-312.pyc,,
zope/exceptions/__pycache__/log.cpython-312.pyc,,
zope/exceptions/exceptionformatter.py,sha256=Lak7E3ciou09BAXQhIKjAuJfAguzqdhCPuxRm7J6MMs,11273
zope/exceptions/interfaces.py,sha256=oVdJiEhKQqop4ZhpWL2yZxkWPgClCAYEAWcZaYy3-RA,3439
zope/exceptions/log.py,sha256=BqabwFXLa4I6KEKvHpPJBHtysKsI4BcFR2VOGIBrnQM,1236
zope/exceptions/tests/__init__.py,sha256=MsSFjiLMLJZ7QhUPpVBWKiyDnCzryquRyr329NoCACI,2
zope/exceptions/tests/__pycache__/__init__.cpython-312.pyc,,
zope/exceptions/tests/__pycache__/test_exceptionformatter.cpython-312.pyc,,
zope/exceptions/tests/__pycache__/test_log.cpython-312.pyc,,
zope/exceptions/tests/test_exceptionformatter.py,sha256=PnPDMAgK3uwHlzkcagN9ArfG51JAfOKCyCp3dh85SpE,36805
zope/exceptions/tests/test_log.py,sha256=RiBEivf9IB-1YuSZpPuBgG1aDrtuRQvYfDBC8xWjA8E,2858
